# Generated by Django 3.1 on 2020-09-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dive', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dive',
            options={'ordering': ['-date']},
        ),
    ]
