# Generated by Django 3.1 on 2020-09-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dive', '0002_auto_20200909_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='avg_depth',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='dive',
            name='current',
            field=models.IntegerField(choices=[(0, 'Negligible'), (10, 'Small'), (20, 'Medium'), (30, 'Strong')], default=10),
        ),
        migrations.AddField(
            model_name='dive',
            name='max_depth',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='dive',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dive',
            name='waves',
            field=models.IntegerField(choices=[(0, 'Negligible'), (10, 'Small'), (20, 'Medium'), (30, 'Large')], default=10),
        ),
        migrations.AlterField(
            model_name='dive',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
