# Generated by Django 3.1 on 2020-09-10 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dive', '0004_auto_20200910_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='bottom_time',
            field=models.PositiveIntegerField(default=30, help_text='Bottom time in minutes.', validators=[django.core.validators.MaxValueValidator(3600)]),
        ),
    ]
