# Generated by Django 3.1 on 2020-09-10 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dive', '0005_auto_20200910_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='avg_depth',
            field=models.PositiveIntegerField(default=10, help_text='Average dive depth in metres.', validators=[django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
