# Generated by Django 3.1 on 2020-09-10 17:39

import dive.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dive', '0006_auto_20200910_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='date',
            field=models.DateField(validators=[dive.validators.validate_past_date]),
        ),
    ]
