# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: requirements-txt-fixer

-   repo: https://gitlab.com/pycqa/flake8
    rev: e897cfac394c9066fc48b2fc120ed03507c97187
    hooks:
    -   id: flake8
