version: '3.7'

services: 
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment: 
            - SECRET_KEY=7k2kf1_f-7*_ycn+^n8y6nx!99)g$$j^1--tfl1#!k4*&d0#+&&
            - DEBUG=1
        volumes:
            - .:/code
        ports: 
            - 8000:8000
        depends_on: 
            - db
    
    db:
        image: postgres:11
        environment: 
            POSTGRES_PASSWORD: postgres
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
volumes: 
    postgres_data:
        
            