[tool.black]
line-length = 88
include = '\.pyi?$'

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
default_section = "THIRDPARTY"
known_first_party = ["dashboard", "users", "sellers", "products", "pages"]
known_third_party = []

[tool.pylint.MESSAGE_CONTROL]
disable="""
    bad-continuation,
    no-else-return,
    too-few-public-methods,
    line-too-long,
    duplicate-code,
    import-error,
    unused-argument,
    no-self-use,
    import-outside-toplevel,
    fixme
"""

[tool.pylint.REPORTS]
reports="no"

[tool.pylint.FORMAT]
max-line-length="88"

[tool.pylint.BASIC]
good-names="_,i,j,k,e,qs,pk,setUp,tearDown"