# Generated by Django 3.0.8 on 2020-07-25 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.CharField(max_length=60, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=60, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(choices=[('uk', 'United Kingdom'), ('us', 'United States of America'), ('ar', 'Argentina')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_mock', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sellers/logo/')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='sellers/headerImage')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
