# Generated by Django 3.1 on 2020-10-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_seller_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
