# Generated by Django 3.1 on 2020-08-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200811_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('special_status', 'Can see all products')]},
        ),
    ]
