# Generated by Django 3.1 on 2020-10-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20200915_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
