# Generated by Django 3.1 on 2020-10-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_auto_20201017_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ('-created_at',)},
        ),
    ]
