# Generated by Django 3.1 on 2020-09-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dive', '0003_auto_20200910_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='bottom_time',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='dive',
            name='current',
            field=models.IntegerField(choices=[(0, 'Negligible'), (10, 'Light'), (20, 'Medium'), (30, 'Strong')], default=10),
        ),
        migrations.AlterField(
            model_name='dive',
            name='visibility',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
