# Generated by Django 3.1 on 2020-09-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200818_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_updated'], 'permissions': [('special_status', 'Can see all products')]},
        ),
    ]
